export const appConfig = {
  model: {
    url: `${import.meta.env.BASE_URL}assets/winline.glb`,
    dracoDecoderPath: `${import.meta.env.BASE_URL}draco/`,
    normalize: true,
    scale: 1,
    position: { x: 0, y: 0, z: 0 },
    rotationDegrees: { x: 0, y: 35, z: 0 },
  },

  camera: {
    // "fit" подгоняет камеру автоматически, "manual" берёт координаты ниже.
    mode: "fit",
    fov: 24,
    near: 0.001,
    far: 100,
    breakpoint: 728,

    manual: {
      desktop: {
        position: { x: 0, y: 0, z: 2 },
        target: { x: 0, y: 0, z: 0 },
      },
      mobile: {
        position: { x: 0, y: 0, z: 2.5 },
        target: { x: 0, y:0, z: 0 },
      },
    },

    fit: {
      // 1 = заполнить 100% ширины, 0.9 = оставить по 5% с каждой стороны.
      mobileWidthFill: 1,
      desktopPadding: 1,
      // Смещение задаёт ракурс и масштабируется вместе с дистанцией камеры.
      positionOffset: { x: 0, y: 1, z: 0 },
      targetOffset: { x: 0, y: 0, z: 0 },
      excludedMeshNames: [
        "Sphere",
        "Sphere_colaider",
        "static_base_colaider",
      ],
      excludedGeometryNames: ["Sphere.020"],
    },
  },

  controls: {
    enabled: false,
    enableDamping: true,
    dampingFactor: 0.06,
    enableRotate: true,
    enableZoom: true,
    enablePan: false,
    minDistance: 0.15,
    maxDistance: Infinity,
  },

  parallax: {
    enabled: true,
    smoothing: 5,
    deadZone: 0.03,
    desktop: {
      cameraX: 0.035,
      cameraY: 0.025,
      backgroundX: 14,
      backgroundY: 10,
    },
    mobile: {
      tiltRangeDegrees: 18,
      cameraX: 0.03,
      cameraY: 0.02,
      backgroundX: 10,
      backgroundY: 7,
    },
  },

  materials: {
    transparentMeshNames: ["Sphere"],
    transparentGeometryNames: ["Sphere.020"],
  },

  physics: {
    enabled: true,
    sphereColliderName: "Sphere_colaider",
    staticBaseColliderName: "static_base_colaider",
    gravity: { x: 0, y: -0.55, z: 0 },
    fixedTimeStep: 1 / 60,
    maxSubSteps: 4,
    ccdSubsteps: 2,
    clipCcdEnabled: false,
    ballCcdEnabled: true,
    additionalSolverIterations: 0,
    clipColliderScale: 0.9,
    ballColliderScale: 0.95,
    clipMass: 0.3,
    clipMassFactorMin: 0.35,
    clipMassFactorMax: 1.65,
    ballMass: 1.8,
    friction: 0.08,
    floorFriction: 0.65,
    restitution: 0.05,
    staticRestitution: 0.03,
    boundaryRestitution: 0.05,
    sphereContactSkin: 0,
    staticBaseColliderThickness: 0.12,
    staticBaseColliderContactSkin: 0.01,
    linearDamping: 2,
    angularDamping: 2.5,
    flightAngularDamping: 0.65,
    launchMinSpeed: 1.25,
    launchMinDistance: 0.025,
    launchWindowSeconds: 0.1,
    launchMaxSpeed: 6,
    launchVelocityMin: 3.2,
    launchVelocityMax: 4,
    launchResponsivenessMin: 0.8,
    launchResponsivenessMax: 1.35,
    launchSpread: 1.1,
    launchRadialVelocity: 0.9,
    launchSwirlVelocity: 1.5,
    launchSpinSpeedMin: 2.2,
    launchSpinSpeedMax: 4.2,
    repeatLiftVelocity: 1.5,
    vortexCoreRatio: 0.35,
    vortexTangentialSpeed: 2.6,
    vortexFlowCoupling: 2.2,
    vortexCenterJitter: 0.3,
    primaryVortexFraction: 0.55,
    reverseVortexFraction: 0.3,
    chaoticTurbulenceMultiplier: 1.8,
    vortexLiftAcceleration: 0.9,
    vortexMinimumLiftRatio: 0.35,
    vortexInwardAcceleration: 0.3,
    vortexDecayRate: 0.5,
    turbulenceAcceleration: 0.85,
    turbulenceFrequencyMin: 0.45,
    turbulenceFrequencyMax: 0.9,
    verticalTurbulenceRatio: 0.08,
    fallGravityScaleMin: 0.55,
    fallGravityScaleMax: 1.45,
    ballFallGravityScale: 1.45,
    fallLinearDampingMin: 0.45,
    fallLinearDampingMax: 1.35,
    ballFallLinearDamping: 0.45,
    fallDriftAcceleration: 0.28,
    fallDriftStrengthMin: 0.8,
    fallDriftStrengthMax: 1.3,
    settleLinearSpeed: 0.06,
    settleAngularSpeed: 0.3,
    settleDelay: 0.6,
    settleCheckInterval: 0.1,
    settleVortexEnergy: 0.04,
    maxLinearSpeed: 7,
    maxAngularSpeed: 4.5,
  },

  renderer: {
    antialias: true,
    maxPixelRatio: 2,
    maxFps: 60,
    showStats: true,
  },
};
